services:
  ultrafeeder:
    image: ghcr.io/sdr-enthusiasts/docker-adsb-ultrafeeder:latest
    container_name: ultrafeeder
    restart: unless-stopped
    environment:
      - TZ=${ULTRAFEEDER_TZ:-America/Sao_Paulo}
      - READSB_NET_CONNECTOR=${ULTRAFEEDER_NET_CONNECTOR:-127.0.0.1,30003,sbs_in}
      - READSB_LAT=${ULTRAFEEDER_LAT:- 0.0}
      - READSB_LON=${ULTRAFEEDER_LON:- 0.0}
      - READSB_ALT=${ULTRAFEEDER_ALT:-0m}
      - READSB_RX_LOCATION_ACCURACY=${ULTRAFEEDER_RX_LOCATION_ACCURACY:-2}
      - READSB_STATS_RANGE=${ULTRAFEEDER_STATS_RANGE:-true}
      - TAR1090_ENABLE=${TAR1090_ENABLE:-true}
      - TAR1090_INTERACTIVE_TTL=${TAR1090_INTERACTIVE_TTL:-3600}
      - TAR1090_RANGE_OUTLINE_COLOR=${TAR1090_RANGE_OUTLINE_COLOR:-green}
      # FlightAware feed, only enable if FA_FEEDER_ID is set
      - FEED_FLIGHTAWARE_ENABLE=${FA_FEEDER_ID:+true}
      - FEED_FLIGHTAWARE_BEASTHOST=${FA_BEASTHOST:-127.0.0.1}
      - FEED_FLIGHTAWARE_BEASTPORT=${FA_BEASTPORT:-30005}
      - FEED_FLIGHTAWARE_ID=${FA_FEEDER_ID}
    ports:
      - "${ULTRAFEEDER_PORT:-2480}:80"

  ingestor:
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    container_name: sbs-ingestor
    restart: unless-stopped
    environment:
      - TZ=${INGESTOR_TZ:-America/Sao_Paulo}
      - SOURCES=${SOURCES:-127.0.0.1:30003}
      - NATS_URL=${NATS_URL:-nats://nats:4222}
    depends_on:
      - nats

  logger:
    build:
      context: .
      dockerfile: Dockerfile.logger
    container_name: sbs-logger
    restart: unless-stopped
    environment:
      - TZ=${LOGGER_TZ:-America/Sao_Paulo}
      - OUTPUT_DIR=${OUTPUT_DIR:-/app/logs}
      - NATS_URL=${NATS_URL:-nats://nats:4222}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - nats

  tracker:
    build:
      context: .
      dockerfile: Dockerfile.tracker
    container_name: sbs-tracker
    restart: unless-stopped
    environment:
      - TZ=${TRACKER_TZ:-UTC}
      - NATS_URL=${NATS_URL:-nats://nats:4222}
      - DB_CONN_STR=${DB_CONN_STR:-postgres://sbs:sbs_password@timescaledb:5432/sbs_data?sslmode=disable}
      - REDIS_ADDR=${REDIS_ADDR:-redis:6379}
    depends_on:
      - nats
      - timescaledb
      - redis

  nats:
    image: nats:latest
    container_name: nats
    restart: unless-stopped
    command: ["-js"]
    volumes:
      - nats_data:/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-sbs}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sbs_password}
      - POSTGRES_DB=${POSTGRES_DB:-sbs_data}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescaledb_data:
  redis_data:
  nats_data:
