name: Docker Hub Publishing

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

env:
  GO_VERSION: '1.23.0'
  DOCKERHUB_NAMESPACE: 'saviobatista'  # Docker Hub username

jobs:
  dockerhub-publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: ingestor
            dockerfile: Dockerfile.ingestor
            description: 'SBS Ingestor Service'
          - service: logger
            dockerfile: Dockerfile.logger
            description: 'SBS Logger Service'
          - service: tracker
            dockerfile: Dockerfile.tracker
            description: 'SBS Tracker Service'
          - service: migrate
            dockerfile: Dockerfile.migrate
            description: 'SBS Database Migration Service'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_NAMESPACE }}/sbs-${{ matrix.service }}
          tags: |
            type=ref,event=release
            type=raw,value=${{ github.event.inputs.version || 'latest' }}
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
          labels: |
            org.opencontainers.image.title=SBS ${{ matrix.service }}
            org.opencontainers.image.description=${{ matrix.description }}
            org.opencontainers.image.vendor=Savio
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Verify image
        run: |
          echo "Verifying image: ${{ steps.meta.outputs.tags }}"
          docker pull ${{ steps.meta.outputs.tags }}
          docker inspect ${{ steps.meta.outputs.tags }} | jq '.[0].Architecture'

  notify:
    name: Notify Success
    runs-on: ubuntu-latest
    needs: dockerhub-publish
    if: always()
    
    steps:
      - name: Notify on success
        if: needs.dockerhub-publish.result == 'success'
        run: |
          echo "✅ Successfully published all images to Docker Hub!"
          echo "📦 Images published:"
          echo "  - saviobatista/sbs-ingestor"
          echo "  - saviobatista/sbs-logger"
          echo "  - saviobatista/sbs-tracker"
          echo "  - saviobatista/sbs-migrate"
          echo "🏷️  Tags: ${{ github.ref_name }}, latest"
          echo "🔗 Docker Hub: https://hub.docker.com/r/saviobatista/sbs-logger"

      - name: Notify on failure
        if: needs.dockerhub-publish.result == 'failure'
        run: |
          echo "❌ Failed to publish images to Docker Hub"
          exit 1 